### ISSUE TITLE
Package dependenices check for DESCRIPTION

### ISSUE THREAD

**Issue by chrismainey** [martinctc/devtoolbox#8]
Hi, just spotted your package and thought I'd try it out.  Installed fine, but I needed to install `visNetwork`, `pkgnet` and `cranlogs.`  I checked the description file to see what else, so I could install easily, but didn't see them listed.  Do they need adding to your Imports?

**Comment by martinctc** [comment]
Thank you @chrismainey - and apologies for the very late reply! This package is out maintained but I am fixing this issue in #9. Thanks for flagging.
